---
dependency:
  name: galaxy
driver:
  name: docker
provisioner:
  name: ansible
verifier:
  name: ansible

platforms:
  - name: ubuntu2204
    image: 'geerlingguy/docker-ubuntu2204-ansible:latest'
    command: ''
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    cgroupns_mode: host

  - name: rockylinux9
    image: 'geerlingguy/docker-rockylinux9-ansible:latest'
    command: ''
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
